itae/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from rango import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^rango/', include('rango.urls')),
	# above maps any URLs starting
	# with rango/ to be handled by
	# the rango application
	url(r'^admin/', admin.site.urls),
]

rango/urls.py
from django.conf.urls import url
from rango import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'rango'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^about/$', views.about, name='about'),
	url(r'^add_category/$', views.add_category, name='add_category'),
	url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
	url(r'^category/(?P<category_name_slug>[\w\-]+)/$',	views.show_category, name='show_category'),
	url(r'^register/$', views.register, name='register'), # New pattern!
	url(r'^login/$', views.user_login, name='login'),
	url(r'^restricted/', views.restricted, name='restricted'),
	url(r'^logout/$', views.user_logout, name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model) :
    name = models.CharField(max_length = 128, unique = True)
    views = models.IntegerField(default = 0)
    likes = models.IntegerField(default = 0)
    slug = models.SlugField(unique = True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Page(models.Model) :
    category = models.ForeignKey(Category)
    title = models.CharField(max_length = 128)
    url = models.URLField()
    views = models.IntegerField(default = 0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)
    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    # Override the __unicode__() method to return out something meaningful!
    # Remember if you use Python 2.7.x, define __unicode__ too!
    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile

class CategoryForm(forms.ModelForm):
	name = forms.CharField(max_length=128, help_text="Please enter the category name.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
	slug = forms.CharField(widget=forms.HiddenInput(), required=False)

	# An inline class to provide additional information on the form.
	class Meta:
		# Provide an association between the ModelForm and a model
		model = Category
		fields = ('name',)

class PageForm(forms.ModelForm):
	title = forms.CharField(max_length=128,	help_text="Please enter the title of the page.")
	url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
	views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

	class Meta:
		# Provide an association between the ModelForm and a model
		model = Page
		# What fields do we want to include in our form?
		# This way we don't need every field in the model present.
		# Some fields may allow NULL values, so we may not want to include them.
		# Here, we are hiding the foreign key.
		# we can either exclude the category field from the form,
		exclude = ('category',)
		# or specify the fields to include (i.e. not include the category field)
		#fields = ('title', 'url', 'views')

	def clean(self):
		cleaned_data = self.cleaned_data
		url = cleaned_data.get('url')
		# If url is not empty and doesn't start with 'http://',
		# then prepend 'http://'.
		if url and not url.startswith('http://'):
			url = 'http://' + url
			cleaned_data['url'] = url
			return cleaned_data

# the form of user registor and its profile
class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())
	class Meta:
		model = User
		fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from rango.forms import PageForm
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from datetime import datetime

# Create your views here.
def index(request):
	# Query the database for a list of ALL categories currently stored.
	# Order the categories by no. likes in descending order.
	# Retrieve the top 5 only - or all if less than 5.
	# Place the list in our context_dict dictionary
	# that will be passed to the template engine.

	#request.session.set_test_cookie()
	category_list = Category.objects.order_by('-likes')[:5]
	page_list = Page.objects.order_by('-views')[:5]
	context_dict = {'categories': category_list, 'pages': page_list }
	# Render the response and send it back!
	#return render(request, 'rango/index.html', context_dict)
	# Call the helper function to handle the cookies
	visitor_cookie_handler(request)
	context_dict['visits'] = request.session['visits']

	# Obtain our Response object early so we can add cookie information.
	response = render(request, 'rango/index.html', context_dict)
	
	# Return response back to the user, updating any cookies that need changed.
	return response

# chapter 3 & 4
#def index(request):
#	context_dict = {'boldmessage': "Crunchy, creamy, cookie, candy, cupcake!"}
#	return render(request, 'rango/index.html', context=context_dict)
	#return HttpResponse("Rango says hey there partner! <br/> <a href='/rango/about/'>About</a>")

def about(request):
	if request.session.test_cookie_worked():
		print("TEST COOKIE WORKED!")
		request.session.delete_test_cookie()

	visitor_cookie_handler(request)
	context_dict = {}
	context_dict['visits'] = request.session['visits']
	return render(request, 'rango/about.html', context=context_dict)

def show_category(request, category_name_slug):
	context_dict = {}
	try:
		category = Category.objects.get(slug = category_name_slug)
		pages = Page.objects.filter(category = category)
		context_dict['pages'] = pages
		context_dict['category'] = category
	except Category.DoesNotExist:
		context_dict['category'] = None
		context_dict['pages'] = None
	return render(request, 'rango/category.html', context_dict)

def add_category(request):
	form = CategoryForm()
	# A HTTP POST?
	if request.method == 'POST':
		form = CategoryForm(request.POST)
		# Have we been provided with a valid form?
		if form.is_valid():
			# Save the new category to the database.
			form.save(commit=True)
			# Now that the category is saved
			# We could give a confirmation message
			# But since the most recent category added is on the index page
			# Then we can direct the user back to the index page.
			return index(request)
		else:
			# The supplied form contained errors -
			# just print them to the terminal.
			print(form.errors)
	# Will handle the bad form, new form, or no form supplied cases.
	# Render the form with error messages (if any).
	return render(request, 'rango/add_category.html', {'form': form})

def add_page(request, category_name_slug):
	try:
		category = Category.objects.get(slug=category_name_slug)
	except Category.DoesNotExist:
		category = None

	form = PageForm()
	if request.method == 'POST':
		form = PageForm(request.POST)
		if form.is_valid():
			if category:
				page = form.save(commit=False)
				page.category = category
				page.views = 0
				page.save()
				return show_category(request, category_name_slug)
		else:
			print(form.errors)
	context_dict = {'form':form, 'category': category}
	return render(request, 'rango/add_page.html', context_dict)

def register(request):
	# A boolean value for telling the template
	# whether the registration was successful.
	# Set to False initially. Code changes value to
	# True when registration succeeds.
	registered = False
	# If it's a HTTP POST, we're interested in processing form data.
	if request.method == 'POST':
		# Attempt to grab information from the raw form information.
		# Note that we make use of both UserForm and UserProfileForm.
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileForm(data=request.POST)
		# If the two forms are valid...
		if user_form.is_valid() and profile_form.is_valid():
			# Save the user's form data to the database.
			user = user_form.save()
			# Now we hash the password with the set_password method.
			# Once hashed, we can update the user object.
			user.set_password(user.password)
			user.save()
			# Now sort out the UserProfile instance.
			# Since we need to set the user attribute ourselves,
			# we set commit=False. This delays saving the model
			# until we're ready to avoid integrity problems.

			profile = profile_form.save(commit=False)
			profile.user = user
			# Did the user provide a profile picture?
			# If so, we need to get it from the input form and
			#put it in the UserProfile model.
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']
				# Now we save the UserProfile model instance.
				profile.save()
				# Update our variable to indicate that the template
				# registration was successful.
				registered = True
		else:
			# Invalid form or forms - mistakes or something else?
			# Print problems to the terminal.
			print(user_form.errors, profile_form.errors)
	else:
		# Not a HTTP POST, so we render our form using two ModelForm instances.
		# These forms will be blank, ready for user input.
		user_form = UserForm()
		profile_form = UserProfileForm()
		# Render the template depending on the context.
	return render(request,'rango/register.html',{'user_form': user_form,'profile_form': profile_form,'registered': registered})

def user_login(request):
	# If the request is a HTTP POST, try to pull out the relevant information.
	if request.method == 'POST':
		# Gather the username and password provided by the user.
		# This information is obtained from the login form.
		# We use request.POST.get('<variable>') as opposed
		# to request.POST['<variable>'], because the
		# request.POST.get('<variable>') returns None if the
		# value does not exist, while request.POST['<variable>']
		# will raise a KeyError exception.
		username = request.POST.get('username')
		password = request.POST.get('password')
		# Use Django's machinery to attempt to see if the username/password
		# combination is valid - a User object is returned if it is.
		user = authenticate(username=username, password=password)
		# If we have a User object, the details are correct.
		# If None (Python's way of representing the absence of a value), no user
		# with matching credentials was found.
		if user:
			# Is the account active? It could have been disabled.
			if user.is_active:
				# If the account is valid and active, we can log the user in.
				# We'll send the user back to the homepage.
				login(request, user)
				return HttpResponseRedirect(reverse('index'))
			else:
				# An inactive account was used - no logging in!
				return HttpResponse("Your Rango account is disabled.")
		else:
			# Bad login details were provided. So we can't log the user in.
			print("Invalid login details: {0}, {1}".format(username, password))
			return HttpResponse("Invalid login details supplied.")
			# The request is not a HTTP POST, so display the login form.
			# This scenario would most likely be a HTTP GET.
	else:
		# No context variables to pass to the template system, hence the
		# blank dictionary object...
		return render(request, 'rango/login.html', {})

def some_view(request):
	if not request.user.is_authenticated():
		return HttpResponse("You are logged in.")
	else:
		return HttpResponse("You are not logged in.")

def restricted(request):
	return HttpResponse("Since you're logged in, you can see this text!")

# Use the login_required() decorator to ensure only those logged in can
# access the view.
@login_required
def user_logout(request):
	# Since we know the user is logged in, we can now just log them out.
	logout(request)
	# Take the user back to the homepage.
	return HttpResponseRedirect(reverse('index'))

def visitor_cookie_handler(request, response):
	# Get the number of visits to the site.
	# We use the COOKIES.get() function to obtain the visits cookie.
	# If the cookie exists, the value returned is casted to an integer.
	# If the cookie doesn't exist, then the default value of 1 is used.
	visits = int(request.COOKIES.get('visits', '1'))
	last_visit_cookie = request.COOKIES.get('last_visit', str(datetime.now()))
	last_visit_time = datetime.strptime(last_visit_cookie[:-7],
	'%Y-%m-%d %H:%M:%S')
	# If it's been more than a day since the last visit...
	if (datetime.now() - last_visit_time).days > 0:
		visits = visits + 1
		# Update the last visit cookie now that we have updated the count
		response.set_cookie('last_visit', str(datetime.now()))
	else:
		visits = 1
		# Set the last visit cookie
		response.set_cookie('last_visit', last_visit_cookie)
	# Update/set the visits cookie
	response.set_cookie('visits', visits)

# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
	val = request.session.get(cookie)
	if not val:
		val = default_val
	return val

# Updated the function definition
def visitor_cookie_handler(request):
	visits = int(get_server_side_cookie(request, 'visits', '1'))
	last_visit_cookie = get_server_side_cookie(request,'last_visit',str(datetime.now()))
	last_visit_time = datetime.strptime(last_visit_cookie[:-7],	'%Y-%m-%d %H:%M:%S')
	# If it's been more than a day since the last visit...
	if (datetime.now() - last_visit_time).days > 0:
		visits = visits + 1
		#update the last visit cookie now that we have updated the count
		request.session['last_visit'] = str(datetime.now())
	else:
		visits = 1

templates/rango/about.html
<!DOCTYPE html>
{% load staticfiles %} <!-- New line -->
<html>
<head>
<title>Rango</title>
</head>
<body>

<div>
<p>visits: {{ visits }}</p>
<h1>This tutorial has been put togatherd by feiguang cao</h1>
	<h1>Rango says here is the about page.</h1>
	<div>
		<a href='/rango/'>Index</a>
		<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" >
		<img src="{{MEDIA_URL}}cat.jpg" alt="Picture of Cat" >
	</div>
</div>
</body>
</html>

templates/rango/add_category.html
<!DOCTYPE html>
<html>
<head>
<title>Rango</title>
</head>
<body>
<h1>Add a Category</h1>
<div>
<form id="category_form" method="post" action="/rango/add_category/">
{% csrf_token %}
{% for hidden in form.hidden_fields %}
{{ hidden }}
{% endfor %}
{% for field in form.visible_fields %}
{{ field.errors }}
{{ field.help_text }}
{{ field }}
{% endfor %}
<input type="submit" name="submit" value="Create Category" />
</form>
</div>
</body>
</html>

templates/rango/add_page.html
<!DOCTYPE html>
<html>
<head>
	<title>add_page</title>
</head>
<body>
<div>
	<a href="{% url 'rango:index' %}">Index</a>



	{% if category %}
		<h1>Add a Page</h1>
		<div>
			<form id = "page_form" method = "post" action = "{% url 'rango:add_page' category.slug %}">
				<!-- csrf is Cross Site Request Forgery Tokens -->
				{% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				{% for field in form.visible_fields %}
					{{ fields.errors}}
					{{ field.help_text }}
					{{ field }}
				{% endfor %}
				<input type="submit" name="submit" value = "Add Page" />
			</form>
		</div>
	{% else %}
		A category by this name does not exist
	{% endif %}

</body>
</html>

templates/rango/base.html
<!DOCTYPE html>
<html>
<head lang = "en">
	<meta charset="utf-8">
	<title>Rango - 
			{% block title_block %}
				How to Tango with Django!
			{% endblock %}
	</title>
</head>
<body>
	<div>
		<ul>
			<li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
			<li><a href="{% url 'rango:about' %}">About</a></li>
			<li><a href="{% url 'rango:index' %}">Index</a></li>
			<li><a href="{% url 'rango:register' %}">Sign Up</a></li>
		</ul>
	</div>
	<hr/>
	<div>
		{% block body_block %}
			This is body_block's default content.
		{% endblock %}
	</div>
</body>
</html>

templates/rango/category.html
<!DOCTYPE html>
<html>
<head>
<title>Rango</title>
</head>
<body>
	<div>
		<a href="/rango/">Index</a><br />
		{% if category %}
			<h1>{{ category.name }}</h1>
			{% if pages %}
			<ul>
				{% for page in pages %}
				<li><a href="{{ page.url }}">{{ page.title }}</a></li>
				{% endfor %}
			</ul>
			{% else %}
			<strong>No pages currently in category.</strong>
			{% endif %}
			<a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br/>
		{% else %}
			The specified category does not exist!
		{% endif %}
	</div>
</body>
</html>

templates/rango/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
<title>Rango</title>
</head>
<body>
<h1>Rango says...</h1>
<div>
{% if user.is_authenticated %}
	howdy {{ user.username }}!
{% else %}
	hey there partner!
{% endif %}
</div>
<div>
	<p>visits: {{ visits }}</p>
	<ul>
		{% if user.is_authenticated %}
		<li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
		<li><a href="{% url 'rango:logout' %}">Logout</a></li>
		{% else %}
		<li><a href="{% url 'rango:login' %}">Sign In</a></li>
		<li><a href="{% url 'rango:register' %}">Sign Up</a></li>
		{% endif %}
		<li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
		<li><a href="{% url 'rango:about' %}">About</a></li>
		<li><a href="{% url 'rango:index' %}">Index</a></li>
	</ul>
	<!--
	<a href="{% url 'rango:register'%}">Register</a><br />
	<a href="{% url 'rango:login' %}">Login</a><br />
	<a href="/rango/add_category/">Add a New Category</a><br />
	-->
	<h5>Most Liked Categories</h5>
{% if categories %}
<ul>
{% for category in categories %}
<!-- Following line changed to add an HTML hyperlink -->
<li>
<a href="{% url 'rango:show_category' category.slug %}">{{ category.name }}</a>
</li>
{% endfor %}
</ul>
{% else %}
<strong>There are no categories present.</strong>
{% endif %}
</div>
<div>
		<h5>Most Viewed Pages</h5>
		{% if pages %}
		<ul>
			{% for page in pages %}
				<li><a href="{{ page.url }}">{{ page.title }}</a></li>
			{% endfor %}
		</ul>
		{% else %}
			<strong>There are no pages present. </strong>
		{% endif %}
	</div>
<div>
<a href="/rango/about/">About Rango</a><br />
<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
</div>
</body>
</html>

<!--
<!DOCTYPE html>
{% load staticfiles %}  New line 
<html>
<head>
<title>Rango</title>
</head>
<body>
<h1>Rango says...</h1>
<div>
hey there partner! <br />
<strong>{{ boldmessage }}</strong><br />
</div>
<div>
<a href="/rango/about/">About</a><br />
<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" /> 
</div>
</body>
</html>

-->

templates/rango/login.html
<!DOCTYPE html>
<html>
<head>
	<title>Rango - Login</title>
</head>
<body>
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
{% csrf_token %}
Username: <input type="text" name="username" value="" size="50" />
<br />
Password: <input type="password" name="password" value="" size="50" />
<br />
<input type="submit" value="submit" />
</form>
</body>
</html>

templates/rango/register.html
<!DOCTYPE html>
<html>
<head>
	<title>Rango - Register</title>
</head>
<body>
	<h1>Register for Rango</h1>
	{% if registered %}
		Rango says: <strong>thank you for registering!</strong>
		<a href="{% url 'index' %}">Return to the homepage.</a><br />
	{% else %}
		Rango says: <strong>register here!</strong><br />
		<form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
		{% csrf_token %}

		<!-- Display each form -->
		{{ user_form.as_p }}
		{{ profile_form.as_p }}

		<!-- Provide a button to click to submit the form. -->
		<input type="submit" name="submit" value="Register" />
		</form>
	{% endif %}
</body>
</html>